[package]
name = "rusty-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "*", package = "gtk4" , features = ["v4_8"] }
sysinfo = "0.28.4"
glib = "*"
